apiVersion: v1
kind: Service
metadata:
  labels:
    app: bx-game-app
  name: bx-game-app-service
  namespace: 4-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bx-game-app
    version: 7.4.0
    env: dev
  type: NodePort