apiVersion: v1
kind: Namespace
metadata:
  name: minio-dev # Change this value if you want a different namespace name
  labels:
    name: minio-dev # Change this value to match metadata.name
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-dev
spec:
  containers:
    - name: minio
      image: quay.io/minio/minio:latest
      command:
        - /bin/bash
        - -c
      args:
        - minio server /data --console-address :9090
      volumeMounts:
        - mountPath: /data
          name: localvolume
  volumes:
    - name: localvolume
      hostPath:
        path: /mnt/disk1/data
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
  namespace: minio-dev
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30040
      name: webconsole
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30041
      name: api
  selector:
    app: minio
  type: NodePort